spring:
  security:
    user:
      name: catalogue
      password: '{noop}password'
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update